packages = [
  "alacritty",
  "bin",
  "bat",
  "cargo",
  "delta",
  "electron",
  "git",
  "gpg",
  "imv",
  "lsd",
  "mako",
  "nvim",
  "opencode",
  "podman",
  "ssh",
  "starship",
  "swappy",
  "sway",
  "swaylock",
  "sworkstyle",
  "uwsm",
  "waybar",
  "wofi",
  "xdg",
  "zsh",
]

[files]
"opencode/opencode.jchacking-pc.json" = "~/.config/opencode/opencode.json"
"sway/monitor.jchacking-pc" = "~/.config/sway/monitor"

[variables]
hardware.hasBattery = false
hardware.isGraphicNvidia = true
